### ISSUE TITLE
reportVersion freeze execution

### ISSUE THREAD

**Issue by marabesi** [ThomasWeinert/carica-firmata#4]
I was trying to execute the `blink-loop.php` script and couldn't get it working with arduino uno.

Debugging through the code I found that the call to the method `reportVersion` is freezing and nothing else work.

Is it something with my setup?

**Comment by ThomasWeinert** [comment]
It is part of the Firmata bootstrap. Make sure that the Firmata server and the connection works (I use the Firmata test program for that.)

If the test program works, we will need to debug the connection a little more.

**Comment by marabesi** [comment]
I tried the same example with node and it worked.

which firmata test program did you use?

**Comment by marabesi** [comment]
<img width="774" alt="screen shot 2017-03-26 at 22 18 51" src="https://cloud.githubusercontent.com/assets/2129872/24337336/3e5f872c-1272-11e7-8044-95b7834a3eaa.png">

**Comment by marabesi** [comment]
up

**Comment by ThomasWeinert** [comment]
I refactored the activation method to try again internally if it does not receive the expected messages after several seconds.
